import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilRootProvider from "@/recoil/RecoilUserState";
import NavigationMenu from "@/components/NavigationMenu";
import { Blinker } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });
const blinker = Blinker({ subsets: ['latin'], weight: ['400', '700'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={blinker.className}>
        <RecoilRootProvider>
          <>
            {children}
          </>
        </RecoilRootProvider>

      </body>
    </html>
  );
}
